In [1]:
from wbfm.utils.feature_detection.utils_networkx import calc_icp_matches

In [22]:
%load_ext autoreload
%autoreload 2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from wbfm.utils.projects.finished_project_data import ProjectData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
fname = "/scratch/zimmer/Charles/dlc_stacks/worm3-2021_09_29/project_config.yaml"
project_data = ProjectData.load_final_project_data_from_config(fname)

Project data for directory:
/scratch/zimmer/Charles/dlc_stacks/worm3-2021_09_29 
Found the following raw data files:
red_data: True
green_data: True
============Segmentation===============
raw_segmentation: True
segmentation: False
============Tracklets==================
df_training_tracklets: True
reindexed_masks_training: True
============Traces=====================
red_traces: False
green_traces: False
final_tracks: True
behavior_annotations: True



In [32]:
i_time = 0
max_dist = 1.0

zxy_from_seg = project_data.get_centroids_as_numpy(i_time)

df = project_data.final_tracks.copy()
all_neurons = list(df.columns.levels[0])
coords = ['z', 'x', 'y']
zxy_from_tracks = np.array([df[n][coords].iloc[i_time].to_numpy() for n in all_neurons])

In [42]:
%%time
algorithm = 'brute'
neighbors_of_seg = NearestNeighbors(n_neighbors=1, radius=max_dist, algorithm=algorithm).fit(zxy_from_seg)

all_matches = [(i, neighbors_of_seg.kneighbors([zxy])[1][0][0]) for i, zxy in enumerate(zxy_from_tracks)]

CPU times: user 83.8 ms, sys: 4.26 ms, total: 88.1 ms
Wall time: 284 ms


In [34]:
%%time
algorithm = 'kd_tree'
neighbors_of_seg = NearestNeighbors(n_neighbors=1, radius=max_dist, algorithm=algorithm).fit(zxy_from_seg)

all_matches = [(i, neighbors_of_seg.kneighbors([zxy])) for i, zxy in enumerate(zxy_from_tracks)]

CPU times: user 100 ms, sys: 1.79 ms, total: 102 ms
Wall time: 430 ms


In [35]:
%%time
algorithm = 'ball_tree'
neighbors_of_seg = NearestNeighbors(n_neighbors=1, radius=max_dist, algorithm=algorithm).fit(zxy_from_seg)

all_matches = [(i, neighbors_of_seg.kneighbors([zxy])) for i, zxy in enumerate(zxy_from_tracks)]

CPU times: user 114 ms, sys: 3.36 ms, total: 117 ms
Wall time: 147 ms


In [20]:
for n0, n1 in zip(zxy_from_seg, zxy_from_tracks):
    print(np.linalg.norm(n0-n1))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.793631766569996
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12.18593654139226
0.0
0.0
12.882213175335648
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6.446992945388486
0.0
0.0
0.0
0.0


In [47]:
zxy_from_seg[35], zxy_from_tracks[10]

(array([  8.7414248 , 282.25593668, 298.18733509]),
 array([  8.7414248 , 282.25593668, 298.18733509]))

In [45]:
neighbors_of_seg.kneighbors(zxy_from_tracks)

(array([[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [7.62939453e-06],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [1.07895932e-05],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [7.62939453e-06],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [7.62939453e-06],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.0